apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-devops-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcp
  template:
    metadata:
      labels:
        app: gcp
    spec:
      containers:
      - name: gcp-devops-gke
        image: us-west1-docker.pkg.dev/kodekloud-gke-practice/gcp-devops-project/python-docker-image-dev:latest
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"

---

apiVersion: v1
kind: Service
metadata:
  name: gcp-devops-gke-service
  namespace: "gcp-devops-dev"
  labels:
    app.kubernetes.io/managed-by : "gcp-cloud-build-deploy"
spec:
  selector:
    app: gcp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
